apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: analytics-service-scaledobject
  namespace: streaming-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics-service
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
    - type: prometheus  #not using redis, using prometheus since its scraping events from endpoints
      metadata:
        serverAddress: http://prometheus-service.streaming-platform.svc.cluster.local:9090
        metricName: analytics_total_events
        threshold: "100"
