apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: redis-auth
  namespace: streaming-platform
spec:
  secretTargetRef:
    - parameter: password
      name: redis-secret 
      key: password