apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: streaming-platform
spec:
  selector:
    app: delivery-service
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP