apiVersion: apps/v1
kind: Deployment
metadata:
  name: encoding-service
  namespace: streaming-platform
  labels:
    app: encoding-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encoding-service
  template:
    metadata:
      labels:
        app: encoding-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - encoding-service
              topologyKey: kubernetes.io/hostname
      containers:
      - name: encoding-service
        image: your-registry/encoding-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: "redis-service.streaming-platform.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: SERVICE_NAME
          value: "encoding"
        resources:   #going to split based on Workload requirement
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        livenessProbe: default
          httpGet:
            path: /api/v1/encoding/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5

